Admin_Page/Models/AuthorizeCode.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Page.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizeCode
    {
        public AuthorizeCode()
        {
        }

        public AuthorizeCode(int id, string newCode, DateTime createdDate, DateTime endDate)
        {
            codeId = id;
            code = newCode;
            createDate = createdDate;
            expiredDate = endDate;
        }

        public int codeId { get; set; }
        public string code { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime expiredDate { get; set; }
    }
}

Admin_Page/Controllers/AuthorizeCodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Admin_Page.Models;

namespace Admin_Page.Controllers
{
    public class AuthorizeCodesController : Controller
    {
        private DB_Entity db = new DB_Entity();

        // GET: AuthorizeCodes
        public ActionResult Index()
        {
            return View(db.AuthorizeCodes.ToList());
        }

        // GET: AuthorizeCodes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorizeCode authorizeCode = db.AuthorizeCodes.Find(id);
            if (authorizeCode == null)
            {
                return HttpNotFound();
            }
            return View(authorizeCode);
        }

        // GET: AuthorizeCodes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AuthorizeCodes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codeId,code,createDate,expiredDate")] AuthorizeCode authorizeCode)
        {
            if (ModelState.IsValid)
            {
                db.AuthorizeCodes.Add(authorizeCode);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(authorizeCode);
        }

        // GET: AuthorizeCodes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorizeCode authorizeCode = db.AuthorizeCodes.Find(id);
            if (authorizeCode == null)
            {
                return HttpNotFound();
            }
            return View(authorizeCode);
        }

        // POST: AuthorizeCodes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codeId,code,createDate,expiredDate")] AuthorizeCode authorizeCode)
        {
            if (ModelState.IsValid)
            {
                db.Entry(authorizeCode).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(authorizeCode);
        }

        // GET: AuthorizeCodes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorizeCode authorizeCode = db.AuthorizeCodes.Find(id);
            if (authorizeCode == null)
            {
                return HttpNotFound();
            }
            return View(authorizeCode);
        }

        // POST: AuthorizeCodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AuthorizeCode authorizeCode = db.AuthorizeCodes.Find(id);
            db.AuthorizeCodes.Remove(authorizeCode);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Admin_Page/Controllers/StoreController.cs
using Admin_Page.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin_Page.Controllers
{
    [UserAuthenticationFilter]
    public class StoreController : Controller
    {
        // GET: Store
        [ValidateAntiForgeryToken]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Admin_Page/Views/Store/Generate_Code.cshtml
@{
    ViewBag.Title = "Generate_Code";
}

<h2>Generate_Code</h2>

Admin_Page/Views/Store/Index.cshtml
@using Admin_Page.Models
@model AuthorizeCode
@{
    ViewBag.Title = "Authorized Code";
}

<h2>@ViewBag.Title</h2>

@*@Html.BeginForm("GenerateCode", "Store", new { ReturnUrl = Model.ReturnUrl }){

    }*@
@Html.ActionLink("Generate", "GenerateCode", "Store", new { @class = "btn btn-outline-secondary btn-lg rounded mx-auto d-block" })
@{
    if (Model == null)
    {
    }
    else
    {
    <p class="text-center mt-5 h1">
        @Model.code
    </p>
        
  
       
    }
}

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

Admin_Page/Views/Store/_AuthorizeCode.cshtml
@model Admin_Page.Models.AuthorizeCode

@{
    if (Model == null)
    {
        <h2> CLM </h2>
    }
    else
    {
        using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100", role = "form" }))
        {
            <div class="input-group">
                @Html.TextBox(Model.code,null, new { @class = "form-control bg-light border-0 small" })
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        }
    }
}